services:
  - type: web
    name: moodssite
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: moodssite
          property: port
    disk:
      name: uploads
      mountPath: /opt/render/project/src/games
      sizeGB: 1