services:
  - type: web
    name: moodssite
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: moodssite
          property: port
      - key: DATABASE_URL
        sync: false